dist:
  name: otelcol-jupyter
  description: A custom OTel Collector distribution for Jupyter Lab Extension
  output_path: ./otelcol-jupyter
  otelcol_version: 0.82.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.82.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.82.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.82.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.82.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.82.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter v0.82.0

extensions:
  - gomod:
      go.opentelemetry.io/collector/extension/ballastextension v0.82.0
  - gomod:
      go.opentelemetry.io/collector/extension/zpagesextension v0.82.0

replaces:
  - go.opentelemetry.io/collector/exporter/otlphttpexporter => ../custom-exporter/otlphttpexporter
