extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: localhost:55679

receivers:
  otlp:
    protocols:
      http:
        cors:
            allowed_origins: [ "http://localhost:8888" ]
            allowed_headers: ["*"]
        endpoint: localhost:4318

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  resource:
    attributes:
      - key: workspaceId
        value: ${env:WORKSPACE_ID}
        action: insert

exporters:
  logging:
    verbosity: detailed
  otlphttp:
    endpoint: "https://telemetry.mentoracademy.org/telemetry-edtech-labs-si-umich-edu/dev/otel"
    compression: none
  # awss3:
  #   s3uploader:
  #       region: 'us-east-1'
  #       s3_bucket: 'telemetry-edtech-labs-si-umich-edu'
  #       s3_prefix: 'dev/openTelemetryTest'
  #       s3_partition: 'minute'
  #       endpoint: 'https://telemetry.mentoracademy.org'
  # awss3:
  #   s3uploader:
  #       region: 'us-east-1'
  #       s4_bucket: 'otel-jupyter'
  #       s3_prefix: 'dev'
  #       s3_partition: 'hour'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging, otlphttp]

  extensions: [memory_ballast, zpages]
